### ISSUE TITLE
Compatibility Midi-Qol and Better Rolls

### ISSUE THREAD

**Issue by Fridan99** [ElfFriend-DnD/foundryvtt-items-with-rolltables-5e#1]
Any possibility to make it compatible with Midi-Qol and Better Rolls?

**Comment by akrigline** [comment]
My current point of view is that this modification mimics an implementation on the core system and thus rolling modifiers should support it.

I'll take a look at Midi and see if I can contribute that support there, I'm not terribly invested in Better Rolls though.
